- 5.5/System/Automation workflows/Give admin access
Because that would fail anyway.
> Do not publish replaced assets to Admin access

- DC/5.6.0/members.dcl
I will merge this as soon as https://github.com/Digizuite/digizuite.core/pull/1281 is merged.
> Fixed typo in member firstname property

- DC/5.6.0/destinations.dcl
- DC/5.6.0/digizuite_constants.dcl
- DC/5.6.0/variables.dcl
Include ShareName part in Storage Variable
> DAM-5843 Included sharename in Storage Variable

- DC/5.6.0/destinations.dcl
was missing a some variable changes due to file not saved
> DAM-5843 Missing variable.storage fixes

- DC/5.6.0/Searches/GetDownloadQualities.dcl
Added GetDownloadQualities search
> DAM-6006 Added dcl for GetDownloadQualities seearch

- DC/5.7.0/Groups/User type/groups.dcl
> Make superadministrator group able to publish assets

- DC/5.8.0/asset_type_configurations.dcl
- DC/5.8.0/asset_type_configurations_upload_quality.dcl
https://digizuite.atlassian.net/browse/DAM-6500
> DAM-6500   Create DCLs for Asset type configuration in the base layer

- DC/5.8.0/Metadata/digizuite_dam_center/config/assets_per_page.dcl
> Remove item security entries for EditComboValue configuration

- MM/5.8.0/config/media_manager_5/fields/theming_details.dcl
> MM5-4976 Remove default value from theming_details config

- MM/5.8.0/config/media_manager_5/labels/Settings.dcl
https://digizuite.atlassian.net/browse/MM5-5033
> task/MM5-5033: UI for global configuration

- MM/5.8.0/config/media_manager_5/labels/Brand Portal.dcl
> MM5-5197 Update brandportal settings labels

- MM/5.8.0/config/media_manager_5/labels/Workflow Management.dcl
> MM5-3860 add wf editor labels

- MM/5.8.0/config/media_manager_5/labels/Audit Trail.dcl
> MM5-5216 access labels

- MM/5.8.0/config/media_manager_5/labels/Audit Trail.dcl
Fixed bugs preventing MM layer from being added
* Duplicated resource label audit_trail_column_author
* Resource for Key 'AUDIT_TRAIL_MEMBER_NAME' was duplicating resource audit_trail_group_name  - renamed to audit_trail_member_name 
* Missing leading ' in key assignment
> Fix mm dcl bug

- MM/5.9.0/config/media_manager_5/labels/Metadata.dcl
JIRA ticket: https://digizuite.atlassian.net/browse/MM5-4886
> task/MM5-4886: Add metadata group navigation

- MM/5.9.0/config/media_manager_5/labels/Metadata.dcl
https://digizuite.atlassian.net/browse/MM5-4886
> task/MM5-4886: Add metadata group navigation, update translations

- MM/5.9.0/config/media_manager_5/labels/Preview Asset.dcl
A 5.9 label to approve by Magnus, since Mathias is on vacation
> refresh metadata label

- MM/5.8.0/config/media_manager_5/labels/Asset List.dcl
- MM/5.9.0/config/media_manager_5/labels/Asset List.dcl
existed for a while, but seems to have been forgotten
> DAM-7006 Add labels for sha1hash, md5hash and deletedDate, which has 

- MM/5.9.0/config/media_manager_5/labels/Asset List.dcl
- MM/5.9.0/config/media_manager_5/labels/Member Management.dcl
- MM/5.9.0/config/media_manager_5/labels/Settings.dcl
- MM/5.9.0/config/media_manager_5/labels/Workflow Management.dcl
- MM/5.9.0/config/media_manager_5/labels/Z Misc Labels.dcl
[MM5-4381](https://digizuite.atlassian.net/browse/MM5-4381)
[MM5-4381]: https://digizuite.atlassian.net/browse/MM5-4381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add "Instantiate workflow" labels

- MM/5.9.0/config/media_manager_5/labels/Workflow Management.dcl
> MM5-3860 Add labels

- MM/5.9.0/config/media_manager_5/labels/Selected Assets.dcl
Just copied labels from 5.8 to 5.9
> MM5-5604 Add label

- MM/5.9.0/config/media_manager_5/labels/Preview Asset.dcl
> MM5-5633 Add labels

- DC/5.10.0/mail_templates/assetsharedbyemail.dcl
- DC/5.9.0/mail_templates/assetsharedbyemail.dcl
[DAM-7259](https://digizuite.atlassian.net/browse/DAM-7259)
- added asset shared by email template
[DAM-7259]: https://digizuite.atlassian.net/browse/DAM-7259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DAM-7259 Email not reeived when sharing a single asset by email

- MM/5.10.0/config/media_manager_5/labels/Asset Preview.dcl
- MM/5.9.0/config/media_manager_5/labels/Asset Preview.dcl
https://digizuite.atlassian.net/browse/MM5-5726
> handle asset warning labels

- MM/5.10.0/config/media_manager_5/fields/asset_list_fields.dcl
https://digizuite.atlassian.net/browse/MM5-5647
According to the jira task, I'm adding footerEnabled and footer text config properties
> asset list footer config

- MM/5.10.0/config/media_manager_5/labels/Asset Preview.dcl
- MM/5.9.0/config/media_manager_5/labels/Asset Preview.dcl
> MM5-5837 Update label

- MM/5.10.0/config/media_manager_5/labels/Freetext Search.dcl
> fix advanced search labels for 5.10

- MM/5.10.0/config/media_manager_5/fields/salesforce_connector_azure_code.dcl
- MM/5.10.0/config/media_manager_5/fields/salesforce_connector_azure_url.dcl
- MM/5.10.0/config/media_manager_5/fields/salesforce_connector_client_base_auth.dcl
- MM/5.10.0/config/media_manager_5/fields/salesforce_connector_client_id.dcl
- MM/5.10.0/config/media_manager_5/fields/salesforce_connector_client_redirect_url.dcl
- MM/5.10.0/config/media_manager_5/fields/salesforce_connector_client_secret.dcl
> sf, adding fields for mm config

- MM/5.9.0/config/media_manager_5/fields/salesforce_connector_azure_code.dcl
- MM/5.9.0/config/media_manager_5/fields/salesforce_connector_azure_url.dcl
- MM/5.9.0/config/media_manager_5/fields/salesforce_connector_client_base_auth.dcl
- MM/5.9.0/config/media_manager_5/fields/salesforce_connector_client_id.dcl
- MM/5.9.0/config/media_manager_5/fields/salesforce_connector_client_redirect_url.dcl
- MM/5.9.0/config/media_manager_5/fields/salesforce_connector_client_secret.dcl
- MM/5.9.0/config/media_manager_5/labels/Settings.dcl
> sf, adding config for salesforce to mm 5.9.0

- DC/5.10.0/destinations/asset_storage_azure.dcl
- DC/5.10.0/destinations/frontend_zip_download_azure.dcl
- DC/5.10.0/destinations/frontenddata_azure.dcl
- DC/5.10.0/destinations/frontenddata_no_security_azure.dcl
- DC/5.10.0/variables.dcl
JIRA ticket: https://digizuite.atlassian.net/browse/DAM-7072
Linked core PR: https://github.com/Digizuite/digizuite.core/pull/2390
> DAM-7072 Remove configurable credentials for blob storage destinations

- MM/5.10.0/config/media_manager_5/labels/Download.dcl
https://digizuite.atlassian.net/browse/MM5-5669
> feature/MM5-5669: Improved UI for unrecommended download qualities

- MM/5.10.0/config/media_manager_5/labels/Workflow Management.dcl
The quality status is now is now updated + plus some new
> MM5 5845 labels

- MM/5.10.0/config/media_manager_5/labels/Download.dcl
https://digizuite.atlassian.net/browse/MM5-5879
> task/MM5-5879: Remove old code relating to digi-download-custom-quality

- MM/5.10.0/config/media_manager_5/labels/Collections.dcl
https://digizuite.atlassian.net/browse/MM5-5936
> feature/MM5-5936: Ability to share a specific asset format

- MM/5.10.0/config/media_manager_5/labels/Collections.dcl
https://digizuite.atlassian.net/browse/MM5-5936
> feature/MM5-5936: Add rendition to the asset share edit form

- MM/5.10.0/config/media_manager_5/labels/Inputs.dcl
- MM/6.0.0/config/media_manager_5/labels/Inputs.dcl
https://digizuite.atlassian.net/browse/MM5-5846
> mm5-5846-label-change

- MM/5.10.0/config/media_manager_5/labels/Asset List.dcl
The only thing done is the name of the titles. 
this just need approval
The danish/english word is not touched!!
> refactored labels

- OOBE/6.0.0/automations/oobe_republish_on_frameaccurate_thumbnail_changed.dcl
https://digizuite.atlassian.net/browse/DAM-7563
> DAM-7563 Fix OOBE automation not appliying due to removed automation action

- MM/6.0.0/config/media_manager_5/labels/Administration.dcl
> MM5-6035 Add labels

- MM/6.0.0/config/media_manager_5/labels/Administration.dcl
> MM5-6051 Add channel labels

- DC/6.0.0/asset_type_extension.dcl
- MM/6.0.0/config/media_manager_5/labels/Download.dcl
https://digizuite.atlassian.net/browse/DAM-7626
Added missing asset type extensions and fixed a small typo.
> DAM-7626 Added missing asset type extensions

- MM/6.0.0/config/media_manager_5/labels/Settings.dcl
https://digizuite.atlassian.net/browse/MM5-6090
> task/MM5-6090: Move Accelerated search status to Logs & Status section

- MM/5.10.0/config/media_manager_5/labels/Administration.dcl
- MM/6.0.0/config/media_manager_5/labels/Administration.dcl
https://digizuite.atlassian.net/browse/DAM-7630
> DAM-7630 Add labels for member filters in analytics

- MM/6.0.0/config/media_manager_5/labels/Asset List.dcl
> MM5-6184 Add label

- MM/6.1.0/config/media_manager_5/labels/Administration.dcl
[MM5-6146](https://digizuite.atlassian.net/browse/MM5-6146): updated/created asset audit trail and system audit trail
[MM5-6146]: https://digizuite.atlassian.net/browse/MM5-6146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MM5-6146 updated/created asset audit trail and system audit trail

- DC/6.0.0/mail_templates/standardheader.dcl
- DC/6.1.0/mail_templates/standardheader.dcl
> DAM-7742 Update url to new logo

- MM/6.1.0/config/media_manager_5/labels/Administration.dcl
https://digizuite.atlassian.net/browse/MM5-5987
> feature/MM5-5989: Insights: Format Filter UI, Descriptive Statistics UI

- MM/6.1.0/config/media_manager_5/labels/Administration.dcl
> MM5-6253 added translations for remove group from user modal

- DC/6.1.0/member_groups/user_type/administrator_22.dcl
- DC/6.1.0/member_groups/user_type/super_administrator.dcl
- OOBE/6.1.0/member_groups/user_type/administrator_22.dcl
https://digizuite.atlassian.net/browse/DAM-7812
> DAM-7812 Add roles for asset categories

- DC/6.1.0/member_groups/user_type/super_administrator.dcl
https://digizuite.atlassian.net/browse/DAM-7823
> DAM-7823 Add role for exporting analytics data

- DC/6.1.0/languages.dcl
Blocked by https://github.com/Digizuite/digizuite.core/pull/2817
> DAM-7822 Adds azure_language_code and elastic_language_code

- MM/6.0.1/config/media_manager_5/labels/Administration.dcl
https://digizuite.atlassian.net/browse/MM5-6328
> bug/MM5-6328: 6.0 - Not possible to move a user or group from one folder to another

- MM/6.0.1/config/media_manager_5/labels/Administration.dcl
- MM/6.1.0/config/media_manager_5/labels/Administration.dcl
https://digizuite.atlassian.net/browse/MM5-6328
> bug/MM5-6328: Add translations to the release 6.1.0

- KeyShot/6.1.0/sso/id_1.dcl
https://digizuite.atlassian.net/browse/DAM-7884
> DAM-7884 Add verify_refresh_tokens_on_access_key_refresh to hub sso

- MM/6.0.1/config/media_manager_5/labels/Administration.dcl
https://digizuite.atlassian.net/browse/MM5-6284
> task/MM5-6284: UI for configuring asset categories

- MM/6.1.0/config/media_manager_5/labels/Collections.dcl
https://digizuite.atlassian.net/browse/MM5-6402
> bug/MM5-6402: Removing asset from collection does not update automatically

- MM/6.1.0/config/media_manager_5/labels/Asset List.dcl
https://digizuite.atlassian.net/browse/MM5-6287
> task/MM5-6287: Asset Category Update UI

- MM/6.1.0/config/media_manager_5/labels/Administration.dcl
- MM/6.1.0/config/media_manager_5/labels/Asset List.dcl
https://digizuite.atlassian.net/browse/MM5-6287
> task/MM5-6287: Add notification translations

- MM/6.1.0/config/media_manager_5/labels/Administration.dcl
https://digizuite.atlassian.net/browse/MM5-6305
> feature/MM5-6305: Insights: Entity count filter UI

- MM/6.1.0/config/media_manager_5/labels/Selected Assets.dcl
- MM/6.1.0/config/media_manager_5/labels/Z Misc Labels.dcl
https://digizuite.atlassian.net/browse/MM5-6457
> task/MM5-6457: Add ability to change asset category for multiple assets

- MM/6.1.0/config/media_manager_5/labels/Administration.dcl
https://digizuite.atlassian.net/browse/MM5-6507
> bug/MM5-6507: User administration: Saving a wrong email will say that the user has a weak password

- DC/6.2.0/asset_relation_types/derived_from.dcl
- DC/6.2.0/asset_relation_types/replace_thumbnails.dcl
- DC/6.2.0/asset_relation_types/replaced_with.dcl
https://digizuite.atlassian.net/browse/DAM-7911
> DAM-7911 Override thumbnails via asset relations

- DC/6.2.0/asset_categories.dcl
See also https://github.com/Digizuite/digizuite.core/pull/3073
> DAM-8064 Specify guid on well known asset categories explicitly

- MM/6.2.0/config/media_manager_5/labels/Administration.dcl
This is the most popupar variant at the system (labels / labels) but I'm not sure, maybe "mærke" will be better
> MM5-6527 added label column to metafields

- MM/6.1.0/config/media_manager_5/labels/Administration.dcl
- MM/6.2.0/config/media_manager_5/labels/Administration.dcl
moved label from 6.2.0 to 6.1.0
> MM5-6527 fixed version

- OOBE/6.2.0/automations/oobe_handle_expired_assets.dcl
https://digizuite.atlassian.net/browse/DAM-7972
> DAM-7972 Remove 'Identity' from cron triggers

- MM/6.2.0/config/media_manager_5/labels/Metadata.dcl
https://digizuite.atlassian.net/browse/MM5-5252
> feature/MM5-5252: Allow users to copy metadata easily and add it to the design in one click in the language they want

- MM/6.2.0/config/media_manager_5/labels/Administration.dcl
https://digizuite.atlassian.net/browse/MM5-6215
> feature/MM5-6215: Insights: Ability to specify the x-axis

- MM/6.2.0/config/media_manager_5/labels/Administration.dcl
https://digizuite.atlassian.net/browse/MM5-6557
> task/MM5-6557: Asset Category GUID UI

- MM/6.2.0/config/media_manager_5/labels/Asset List.dcl
https://digizuite.atlassian.net/browse/MM5-6642
> task/MM5-6642: Remove single relation

- MM/6.2.0/config/media_manager_5/labels/Asset List.dcl
https://digizuite.atlassian.net/browse/MM5-6642
> task/MM5-6642: Add translation for success delete notification

- DC/6.2.0/asset_relation_types/derived_from.dcl
- DC/6.2.0/asset_relation_types/replaced_with.dcl
- DC/6.2.0/asset_relation_types/thumbnail_replacement.dcl
[DAM-8141](https://digizuite.atlassian.net/browse/DAM-8141)
related to [#3173](https://github.com/Digizuite/digizuite.core/pull/3173) changes
[DAM-8141]: https://digizuite.atlassian.net/browse/DAM-8141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DAM-8141 Asset relation type display configuration

- MM/6.2.0/config/media_manager_5/labels/Settings.dcl
https://digizuite.atlassian.net/browse/MM5-6673
> task/MM5-6673: Add Default Search configuration to Administration > Portals

- DC/6.2.0/asset_type_extension.dcl
https://digizuite.atlassian.net/browse/DAM-8170
> added image type to avif

- MM/6.2.0/config/media_manager_5/labels/Administration.dcl
https://digizuite.atlassian.net/browse/MM5-6685
> task/MM5-6685: Update translations after API/UI were changed

- MM/6.2.0/config/media_manager_5/labels/Administration.dcl
https://digizuite.atlassian.net/browse/MM5-6669
> task/MM5-6669: Insights: Group into sections UI improvements

- MM/6.2.0/config/media_manager_5/labels/Administration.dcl
https://digizuite.atlassian.net/browse/MM5-6729
> task/MM5-6729: Replace behavior on Asset relation types admin UI

- MM/6.2.0/config/media_manager_5/labels/Administration.dcl
label appears when filtering by assetId
> integration-label

- KeyShot/6.2.0/asset_relation_types/configurator__still_images.dcl
- KeyShot/6.2.0/asset_relation_types/environment__environment.dcl
- KeyShot/6.2.0/asset_relation_types/environment__textures.dcl
- KeyShot/6.2.0/asset_relation_types/environments__backplates.dcl
- KeyShot/6.2.0/asset_relation_types/materials__textures.dcl
- KeyShot/6.2.0/asset_relation_types/models__backplates.dcl
- KeyShot/6.2.0/asset_relation_types/models__environments.dcl
- KeyShot/6.2.0/asset_relation_types/models__materials.dcl
- KeyShot/6.2.0/asset_relation_types/models__textures.dcl
- KeyShot/6.2.0/asset_relation_types/scene__render_outputs.dcl
- KeyShot/6.2.0/asset_relation_types/scenes__backplates.dcl
- KeyShot/6.2.0/asset_relation_types/scenes__environments.dcl
- KeyShot/6.2.0/asset_relation_types/scenes__geometry.dcl
- KeyShot/6.2.0/asset_relation_types/scenes__materials.dcl
- KeyShot/6.2.0/asset_relation_types/scenes__models.dcl
- KeyShot/6.2.0/asset_relation_types/scenes__textures.dcl
- KeyShot/6.2.0/asset_relation_types/still_image__render_layers.dcl
- KeyShot/6.2.0/asset_relation_types/still_image__render_passes.dcl
https://digizuite.atlassian.net/browse/DAM-8242
> DAM-8242 Rename Source to Primary and Target to Secondary

- MM/6.2.0/config/media_manager_5/labels/Preview Asset.dcl
https://digizuite.atlassian.net/browse/MM5-6768
> task/MM5-6768: Asset relation picker: Add selection counter

- MM/6.2.0/config/media_manager_5/labels/Administration.dcl
> MM5-6818 Add label

- MM/6.2.0/config/media_manager_5/labels/Administration.dcl
https://digizuite.atlassian.net/browse/MM5-6777
> bug/MM5-6777: Allow used asset relation types to be deleted

- MM/6.2.0/config/media_manager_5/labels/Preview Asset.dcl
> MM5-6782 Update labels

- MM/6.2.0/config/media_manager_5/labels/Administration.dcl
https://keyshot.atlassian.net/browse/MM5-6836
> bug/MM5-6836: Cannot make an asset category with assigned assets abstract

- MM/5.10.15/config/media_manager_5/labels/Selected Assets.dcl
- MM/6.2.1/config/media_manager_5/labels/Selected Assets.dcl
- MM/6.3.0/config/media_manager_5/labels/Selected Assets.dcl
> MM5-6887 Update label

- MM/6.3.0/config/media_manager_5/labels/Focused Asset.dcl
https://keyshot.atlassian.net/browse/MM5-6829
> bug/MM5-6829: Override format purposes: Cropping an asset that uses another asset's Large thumbnail is weird

- KeyShot/6.2.0/config/media_manager_5/fields/main_menu_custom_link_enabled.dcl
- KeyShot/6.2.0/config/media_manager_5/fields/main_menu_custom_link_icon.dcl
- KeyShot/6.2.0/config/media_manager_5/fields/main_menu_custom_link_text.dcl
- KeyShot/6.2.0/config/media_manager_5/fields/main_menu_custom_link_url.dcl
- KeyShot/6.2.1/config/media_manager_5/fields/main_menu_custom_link_enabled.dcl
- KeyShot/6.2.1/config/media_manager_5/fields/main_menu_custom_link_icon.dcl
- KeyShot/6.2.1/config/media_manager_5/fields/main_menu_custom_link_text.dcl
- KeyShot/6.2.1/config/media_manager_5/fields/main_menu_custom_link_url.dcl
- KeyShot/6.2.2/config/media_manager_5/fields/main_menu_custom_link_enabled.dcl
- KeyShot/6.2.2/config/media_manager_5/fields/main_menu_custom_link_icon.dcl
- KeyShot/6.2.2/config/media_manager_5/fields/main_menu_custom_link_text.dcl
- KeyShot/6.2.2/config/media_manager_5/fields/main_menu_custom_link_url.dcl
https://keyshot.atlassian.net/browse/DAM-8358
Requested by Lea.
> DAM-8358 Added link to YouTube onboarding videos for Hub.

- MM/6.3.0/config/media_manager_5/fields/multi_file_upload_presets.dcl
https://keyshot.atlassian.net/browse/MM5-6900
> feature/MM5-6900: Create portal configuration page for multi-file upload presets

- DC/6.3.0/member_groups/user_type/administrator_22.dcl
- DC/6.3.0/member_groups/user_type/content_creator.dcl
- DC/6.3.0/member_groups/user_type/light_user_24.dcl
- DC/6.3.0/member_groups/user_type/super_administrator.dcl
- DC/6.3.0/members/system_users_181/system.dcl
- DC/6.3.0/members/user_profiles_213/superadministrator.dcl
- OOBE/6.3.0/member_groups/user_type/administrator_22.dcl
- OOBE/6.3.0/member_groups/user_type/content_creator.dcl
- OOBE/6.3.0/member_groups/user_type/light_user_24.dcl
https://keyshot.atlassian.net/browse/DAM-8383
> DAM-8383 Removed obsolete deleted roles

- MM/6.3.0/config/media_manager_5/labels/Asset List.dcl
https://keyshot.atlassian.net/browse/MM5-6927
> bug/MM5-6927: No validation of timespan in date/time filtering

- MM/6.3.0/config/media_manager_5/labels/Administration.dcl
https://keyshot.atlassian.net/browse/MM5-6944
> task/MM5-6944: Administration: Show all users in root and add Default folder

- MM/6.3.0/config/media_manager_5/labels/Business Workflow.dcl
Translation for MM5-6938
https://keyshot.atlassian.net/browse/MM5-6938
> bug/MM5-6938, addint Tag label

- DC/6.2.3/mail_templates/memberconfirmation.dcl
- DC/6.3.0/mail_templates/memberconfirmation.dcl
https://keyshot.atlassian.net/browse/DAM-8410
> Add member confirmation email template

- DC/6.3.0/member_groups/user_type/administrator_22.dcl
- DC/6.3.0/member_groups/user_type/content_creator.dcl
- DC/6.3.0/member_groups/user_type/super_administrator.dcl
- OOBE/6.3.0/member_groups/user_type/administrator_22.dcl
- OOBE/6.3.0/member_groups/user_type/content_creator.dcl
https://keyshot.atlassian.net/browse/DAM-8392
> Dam 8392. Introduce a 'Can_Live_Export_System_Data' role

- MM/6.3.0/config/media_manager_5/labels/Asset.dcl
https://keyshot.atlassian.net/browse/MM5-6885
#MM5-6885
MM5-6885
correction for labels in asset type
> MM5-6885, change several labels for asset types

- DC/6.3.0/formats/glb_preview.dcl
- DC/6.3.0/formats/ksp.dcl
https://keyshot.atlassian.net/browse/DAM-8323
> DAM-8323 Added a default KSP format

- MM/6.3.0/config/media_manager_5/labels/Config Manager.dcl
https://keyshot.atlassian.net/browse/MM5-7019
> task/MM5-7019: Handle Disabled and System flags on multi-file upload presets

- MM/6.3.0/asset_relation_types/id_360_images.dcl
- MM/6.3.0/config/media_manager_5/fields/three_sixty_viewer_relation_types.dcl
- MM/6.3.0/multi_file_upload_presets/id_360_spin.dcl
https://keyshot.atlassian.net/browse/DAM-8444
> DAM-8444 Initial configuration for 360 spins in the MM layer.

- MM/6.3.0/config/media_manager_5/labels/Upload.dcl
https://keyshot.atlassian.net/browse/MM5-6890
> feature/MM5-6890: Manual upload and relations of multi-file entities

- MM/6.3.0/config/media_manager_5/labels/Upload.dcl
https://keyshot.atlassian.net/browse/MM5-6890
> feature/MM5-6890: Add handling case when preset does not have relations

- MM/6.3.0/config/media_manager_5/labels/Upload.dcl
https://keyshot.atlassian.net/browse/MM5-6890
> feature/MM5-6890: Fix translations for error case on create relations

- MM/6.3.0/config/media_manager_5/labels/Administration Dashboard.dcl
https://keyshot.atlassian.net/browse/MM5-7049
> feature/MM5-7049: Insights: Create table with no column data

- DC/6.4.0/asset_type_extension.dcl
- DC/6.4.0/formats/glb_preview.dcl
https://keyshot.atlassian.net/browse/DAM-8500
> DAM-8500. Rename GLB Preview to GLB in resource format definition

- MM/6.4.0/config/media_manager_5/labels/Administration.dcl
https://keyshot.atlassian.net/browse/MM5-7212
> task/MM5-7212: Check administration metadata section for missing labels

- MM/6.4.0/config/media_manager_5/labels/Administration.dcl
- MM/6.4.0/config/media_manager_5/labels/Authentication.dcl
Danish translations are provided by Claude, but you probably want to doublecheck them. I have agreed with Magnus that translating "Workspace" to "Arbejdsområde" is fine.
> DAM-8553 Workspace management labels

- MM/6.4.0/config/media_manager_5/labels/Administration.dcl
https://keyshot.atlassian.net/browse/MM5-6852
> feature/MM5-7208: UI related to restricted asset category file types

- DC/6.4.0/member_groups/user_type/administrator_22.dcl
- DC/6.4.0/member_groups/user_type/super_administrator.dcl
- DC/6.4.0/members/user_profiles_213/superadministrator.dcl
- OOBE/6.4.0/member_groups/user_type/administrator_22.dcl
See https://github.com/Digizuite/digizuite.core/pull/3591 for more information.
> DAM-8585 Add new roles to configuration

- MM/6.4.0/config/media_manager_5/labels/Administration.dcl
https://keyshot.atlassian.net/browse/MM5-7375
> task/MM5-7375: Insights: Have exclude options in member filter

- DC/6.4.0/mail_templates/invite-existing-user-to-workspace.dcl
- DC/6.4.0/mail_templates/invite-new-user-to-workspace.dcl
https://keyshot.atlassian.net/browse/MM5-7393
> task/MM5-7393: Accept workspace invite

- MM/6.4.0/config/media_manager_5/labels/Business Workflow.dcl
1 Change 'OK' button to 'Create'
2 info label should be "Your new workflow will be a copy of the workflow you select"
3 Name placeholder should be ~~empty~~. removed.
4. Change 'Chose Template..' to Select
> MM5-7446, changing 4 labels for new workflow dialog

- MM/6.4.0/config/media_manager_5/labels/Administration.dcl
> MM5-7505 Update label
